### ISSUE TITLE
Spec: SR-IOV forwarder Device Plugin

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/cmd-forwarder-sriov#20]
User configures Forwarder with the list of PF -> service matches.
```
0000:00:01.0:
  capabilities:
  - intel
  - 10G
  services:
  - serv.dom.a
  - serv.dom.b
0000:00:02.0:
  capabilities:
  - mlx5
  - 10G
  services:
  - serv.dom.b
  - serv.dom.c
```
Forwarder creates all available VFs for the given PFs and generates **tokens**.
```
0000:00:01.0 -> 32 VF -> 32 * { serv.dom.a/intel, serv.dom.a/10G, serv.dom.b/intel, serv.dom.b/10G }
0000:00:02.0 -> 16 VF -> 16 * { serv.dom.b/mlx5, serv.dom.b/10G, serv.dom.c/mlx5, serv.dom.c/10G }

Total:
- 32 * serv.dom.a/intel
- 32 * serv.dom.a/10G
- 32 * serv.dom.b/intel
- 16 * serv.dom.b/mlx5
- 48 * serv.dom.b/10G
- 16 * serv.dom.c/mlx5
- 16 * serv.dom.c/10G
```
In the terms of Device Plugin - **token** is a device. Forwarder advertise tokens. In the beginning all tokens are in **free** state.
Client pod requests tokens.
```
resources:
  limits:
    serv.dom.a/intel: "1"
    serv.dom.b/10G: "1"
```
Device Plugin selects 2 tokens for the client, sets them in **allocated** state and injects theirs IDs into the Client pod via environment variables.
```
NSM_SRIOV_TOKENS=serv.dom.a/intel:c2024bf1,serv.dom.b/10G:ad6167d6
```
Client requests connection using token ID.
```
Request.MechanismPreferences = []{
    {
        Cls: cls.LOCAL,
        Type: vfio.MECHANISM,
        Parameters: {
            tokenID: "ad6167d6",
        },
    },
}
```
Forwarder filters available PFs by token and selects VF for the connection. For the selected VF Forwarder sets passed token in **in use** state and sets 1 token for the other supported by VF token types in **closed** state and marks them as **unhealthy** for the Device Plugin. Tokens to become **closed** first are selected from the **free** tokens, if there is no **free**, tokens are selected from the **allocated** tokens.
```
token: service-b/10G{ad6167d6}
PFs supported:
- 0000:00:01.0
- 0000:00:02.0
VF selected: 0000:00:02.4
token state changes:
- serv.dom.b/10G{ad6167d6} -> in use
- serv.dom.b/mlx5{b6ce9dc3} -> closed + unhealthy
- serv.dom.c/mlx5{a529b8ef} -> closed + unhealthy
- serv.dom.c/10G{5fbffeb4} -> closed + unhealthy
```
When client closes connection, **in use** token becomes **allocated** and all related **closed** tokens become **free** and **healthy** for the Device Plugin.
When client disconnects from the Forwarder, **allocated** token becomes **free**.
