### ISSUE TITLE
Add test Endpoint

### ISSUE THREAD

**Issue by lvfxx** [networkservicemesh/cmd-forwarder-sriov#9]
Add test Endpoint which accepts `Request` with the following parameters
1) `Connection.NetworkService` - the name of the requested network service
2) `Request.MechanismPreferences[].PCIAddress` - each Mechanism(Kernel or VFIO) in `MechanismPreferences` has `PCIAddress` field that contains PCI address of physical function that is available on the Forwarder.

Endpoint selects one of the provided PCI addresses in the `availablePorts` and returns `Connection` with the following parameters:
1) `Mechanism.PCIAddress` - selected PCIAddress.

Endpoint config example
```
resources:
-  res1:
    networkServiceName: service1.example.com
    sourceHostName: example.org
    sourcePCIAddress: 0000:01:00:0
    capability: 10G
    targetMACAddress: 00:0a:95:9d:68:16
-  res 2:
    networkServiceName: service2.example.com
    sourceHostName: example.org
    sourcePCIAddress: 0000:02:00:0
    capability: 100G
    targetMACAddress: 00:1b:44:11:3a:b7
```
